### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by tombenj** [ryanle42/telegramSyndicateBot#1]
@ryanle42 does this work at the current state?

Also, is there an example for `.env.json` file you can provide?

**Comment by sudoryan** [comment]
It should be a working prototype. If not, I can get it running in a few
days. May I ask why you are interested?

**Comment by jinnysunny** [comment]
@ryanle42 I wanted to test it to see how well developed it is and maybe enhance the development. An example for the environment file would be great. Also, are you open for dev work?
